### ISSUE TITLE
导入到当前项目启动报错Class must not be null

### ISSUE THREAD

**Issue by TAO-PAN** [yulichang/mybatis-plus-join#119]
### 当前使用版本(必填,否则不予处理)
1.4.11

### 报错信息
1-2024-03-19 16:17:06 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Class must not be null
        at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:49)
        at com.baomidou.mybatisplus.core.toolkit.Assert.isTrue(Assert.java:38)
        at com.baomidou.mybatisplus.core.toolkit.Assert.notNull(Assert.java:72)
        at com.baomidou.mybatisplus.core.toolkit.ClassUtils.getUserClass(ClassUtils.java:95)
        at com.github.yulichang.toolkit.TableHelper.get(TableHelper.java:45)
        at com.github.yulichang.extension.mapping.mapper.MPJTableInfoHelper.initTableInfo(MPJTableInfoHelper.java:73)
        at com.github.yulichang.extension.mapping.config.MappingConfig.lambda$new$0(MappingConfig.java:17)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.github.yulichang.extension.mapping.config.MappingConfig.<init>(MappingConfig.java:16)
        at com.github.yulichang.autoconfigure.MybatisPlusJoinAutoConfiguration$MPJMappingConfig.onApplicationEvent(MybatisPlusJoinAutoConfiguration.java:132)
        at com.github.yulichang.autoconfigure.MybatisPlusJoinAutoConfiguration$MPJMappingConfig.onApplicationEvent(MybatisPlusJoinAutoConfiguration.java:125)
        at com.github.yulichang.autoconfigure.MybatisPlusJoinAutoConfiguration$MPJMappingConfig$$EnhancerBySpringCGLIB$$c0ff651.onApplicationEvent(<generated>)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)

**Comment by yulichang** [comment]
最好 提供复现工程
