### ISSUE TITLE
 Invalid bound statement (not found)

### ISSUE THREAD

**Issue by Thijsvijver** [yulichang/mybatis-plus-join#26]
Hello,

When running the package I get the following error:
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): {packagename}.{entity}Dao.selectJoinPage
        at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.<init>(MybatisMapperMethod.java:51)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.lambda$cachedInvoker$0(MybatisMapperProxy.java:111)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.baomidou.mybatisplus.core.toolkit.CollectionUtils.computeIfAbsent(CollectionUtils.java:117)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.cachedInvoker(MybatisMapperProxy.java:98)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
        at com.sun.proxy.$Proxy158.selectJoinPage(Unknown Source)

I am running MybatisPlus 3.4.2 with mybatis-plus-join-boot-starter 1.3.11

Online I only find answers that advise me to move my mapper.xml but just like in the example, I don't use an xml.

Thank you in advance!

**Comment by benjak135765** [comment]
add new SelectJoinList()


	@Bean
	@Primary
	public SqlSessionFactory mybatisSqlSessionFactory() throws Exception {
		
		MybatisSqlSessionFactoryBean sessionFactoryBean = new MybatisSqlSessionFactoryBean();
		
		GlobalConfig globalConfig = GlobalConfigUtils.defaults();
		DefaultSqlInjector sqlInjector = new DefaultSqlInjector() {
			@Override
			public List<AbstractMethod> getMethodList(Class<?> mapperClass, TableInfo tableInfo) {
				List<AbstractMethod> methodList=super.getMethodList(mapperClass, tableInfo); 
				methodList.add(new SelectJoinList());  // here
				return methodList;
			}
		};
		globalConfig.setSqlInjector(sqlInjector);
		sessionFactoryBean.setGlobalConfig(globalConfig);
		
		...
		...
		...
		
		
		SqlSessionFactory sqlSessionFactory = sessionFactoryBean.getObject();
		return sqlSessionFactory;
		
	}

**Comment by LiveOrange** [comment]
If  custom extends com.baomidou.mybatisplus.core.injector.DefaultSqlInjector
 replace com.github.yulichang.injector.MPJSqlInjector try.

**Comment by ToryZhou** [comment]
Update DefaultSqlInjector to MPJSqlInjector 
It worked

**Comment by CrazyZfp** [comment]
> If custom extends com.baomidou.mybatisplus.core.injector.DefaultSqlInjector replace com.github.yulichang.injector.MPJSqlInjector try.

没有自定义的注入器，但还是报这个错呢？

**Comment by zhangqiang823** [comment]
同问....是不是版本匹配？

**Comment by yulichang** [comment]
https://mybatisplusjoin.com/pages/problem.html#invalid-bound-statement-not-found
