### ISSUE TITLE
selectJoinCount 报错， java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by sailing0505** [yulichang/mybatis-plus-join#34]
- 版本
<mybatis-plus-join.version>1.4.3</mybatis-plus-join.version>
- 描述
测试selectJoinCount， 抛出异常，日志上看数据库执行都成功了。内部转换失败。测试日志如下

```
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4f664bee] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@1238145834 wrapping com.mysql.cj.jdbc.ConnectionImpl@6befbb12] will not be managed by Spring
==>  Preparing: SELECT COUNT( * ) FROM certificate_revocation t LEFT JOIN crl_operation t2 on t2.revocation_id = t.id WHERE (t.id = ?)
==> Parameters: 1(Integer)
<==    Columns: COUNT( * )
<==        Row: 5
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4f664bee]

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

	at com.sun.proxy.$Proxy93.selectJoinCount(Unknown Source)
	at com.cicv.ma.common.db.mapper.RepoTest.joinTest(RepoTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
```

- 测试代码如下
```
@Test
    public void joinTest() {
        MPJLambdaWrapper lambw = new MPJLambdaWrapper<>()
                .leftJoin(CrlOperation.class, CrlOperation::getRevocationId, CertificateRevocation::getId)
                .eq(CertificateRevocation::getId, 1);

        System.out.println(revocationService.selectJoinCount(qw).longValue());
    }
```

**Comment by yulichang** [comment]
1.4.3.1 修复
