### ISSUE TITLE
使用 orderBy 拼接 SQL，SQL 内的引号会被去掉，导致 SQL 报错

### ISSUE THREAD

**Issue by yamdestiny** [yulichang/mybatis-plus-join#60]
Code:

```java
MPJLambdaWrapper<UserDO> wrapper = MPJWrappers.lambdaJoin();

...

wrapper.orderByAsc("(DECODE(STATUS, 'OPEN', 1, 0))");

return selectJoinPage(page, UserQueryDTO.class, wrapper);
```

Output SQL:

```sql
select xxx from user where deleted=0 order by (DECODE(STATUS, OPEN, 1, 0))
```

Error:

```log
### Cause: java.sql.SQLSyntaxErrorException: ORA-00904: "OPEN": 标识符无效

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00904: "OPEN": 标识符无效

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy120.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:122)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy199.selectJoinPage(Unknown Source)
```

Version:

* `mybatis-plus`: `3.4.2`
* `mybatis-plus-join`: `1.4.5`

DB: Oracle Database 19c

**Comment by yulichang** [comment]
升级版本
