### ISSUE TITLE
mybatis-plus-join和mybatisplus-plus冲突

### ISSUE THREAD

**Issue by arronrose** [yulichang/mybatis-plus-join#72]
使用join引入mpj后正常使用，后来需要多主键更新，引入mybatisplus-plus，@EnableMPP之后，mpj的方法都失效了
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.***.*Mapper.selectJoinPage
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.<init>(MybatisMapperMethod.java:51)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.lambda$cachedInvoker$0(MybatisMapperProxy.java:111)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$$Lambda$735/31656311.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
求助大神解答！

**Comment by fuweixuan** [comment]
哥解决了吗我也遇到了
