### ISSUE TITLE
多个子查询报错

### ISSUE THREAD

**Issue by chrelyonly** [yulichang/mybatis-plus-join#96]
### 当前使用版本(必填,否则不予处理)
MP 3.5.3.1
MPJ 1.4.7.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/yulichang/mybatis-plus-join/assets/62467038/139419a9-4309-41d3-8a45-7788331b53c2)

想这样实现,统计子表的金额与数量
![ec9fa7d321166931bcbabb936fa5fed](https://github.com/yulichang/mybatis-plus-join/assets/62467038/9872250a-c612-441a-92af-6fbbefac5172)
只写一组的话不报错sql且正常
![596046f924c91bdceb8f82631c7e5f0](https://github.com/yulichang/mybatis-plus-join/assets/62467038/245cc05c-f636-482d-9498-d395291e2e5b)

### 重现步骤(如果有就写完整)
主表查询多个子查询,通过主表id  查询子表的数量和费用

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Please do not call the method repeatedly!
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:49) ~[mybatis-plus-core-3.5.3.1.jar:3.5.3.1]
	at com.baomidou.mybatisplus.core.toolkit.Assert.isTrue(Assert.java:38) ~[mybatis-plus-core-3.5.3.1.jar:3.5.3.1]
	at com.github.yulichang.wrapper.MPJAbstractWrapper.setParamAlias(MPJAbstractWrapper.java:704) ~[mybatis-plus-join-core-1.4.7.2.jar:na]
	at com.github.yulichang.wrapper.MPJLambdaWrapper.addCustomWrapper(MPJLambdaWrapper.java:275) ~[mybatis-plus-join-core-1.4.7.2.jar:na]
	at com.github.yulichang.wrapper.MPJLambdaWrapper.selectSub(MPJLambdaWrapper.java:220) ~[mybatis-plus-join-core-1.4.7.2.jar:na]

### 问题
测试发现判断重复用空判断,这个字段我看只用来空判断处理,,可以改进下?
![image](https://github.com/yulichang/mybatis-plus-join/assets/62467038/574e748f-720b-4d15-a3f0-38b19544006d)

**Comment by yulichang** [comment]
1.4.8
